Algoritmo "atividadeManzandoPg66e"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : mostra os valores impares de 0 a 20
// Autor(a)    : Beatriz
// Data atual  : 31/03/2023
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para contador de 0 ate 20 passo 1 faca
  se contador mod 2 <> 0 entao
  escreval(contador)
  fimse
  fimpara

Fimalgoritmo