Algoritmo "atividade55"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Mostra atabuada do 8
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
tabuada, contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 1 ate 10 faca
tabuada<-8*contador
escreval("8 X ",contador," = ",tabuada)
fimpara

Fimalgoritmo