Algoritmo "antecessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : lê um número e msotra seu antecessor
// Autor(a)    : Beatriz
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero, antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número:")
leia(numero)
antecessor<- numero - 1
escreval("O antecessor do número digitado é:", antecessor)

Fimalgoritmo