Algoritmo "atividade52"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : mostra os 10 primeiros números inteiros maiores que 100
// Autor(a)    : Beatriz
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 101 ate 111 faca
escreval(contador)
fimpara

Fimalgoritmo