Algoritmo "atividade50"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : mostra os  números de 1 a 10 em ordem crescente.
// Autor(a)    : Beatriz
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 1 ate 10 faca
escreval(contador)
fimpara

Fimalgoritmo