Algoritmo "sucessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Lê um número e exibe o sucesor
// Autor(a)    : Beatriz
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero, sucessor : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número:")
leia(numero)
sucessor<-numero + 1
escreval("O sucessor do número digitado é: ", sucessor)

Fimalgoritmo