Algoritmo "areacirculo"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Lê o raio do circulo e exibe a area
// Autor(a)    : Beatriz
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
raio: inteiro
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o raio do círculo:")
leia(raio)

area<-raio*raio*3.14

escreval("A área do círculo é:", area)

Fimalgoritmo