Algoritmo "atividade57"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : mostra os numeros de 1 ate 10 com REPITA e um CONTADOR
// Autor(a)    : Beatriz
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
contador<-contador+1
escreval(contador)
ate contador = 10

Fimalgoritmo